services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - migrate

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./run_migrations.sh"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: docker_postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "54321:5432"
